### ISSUE TITLE
Players with spaces in names cant access shop gui

### ISSUE THREAD

**Issue by TalhaAzeem37** [Leonidius20/TradingInterface#1]
When players with space in their names try to access the shop GUI, it prevents it by saying "unknown command". This is a major bug on my server, so please fix it ASAP. Thank you!

**Comment by Leonidius20** [comment]
It seems like it's Nukkit's bug. Do players with spaces in names experience the same problem with other commands or is it just a problem of this one?

**Comment by unixcmddev** [comment]
Yeah, may be a Nukkit bug. Same problem happened with another plugin, but the creator managed to fix that, can you do the same?

**Comment by unixcmddev** [comment]
You got discord? It’ll be easier for me to contact you then.

**Comment by Leonidius20** [comment]
@unixcmddev Yeah, I do have a Discord. My nickname there is Leonidius

**Comment by Leonidius20** [comment]
@unixcmddev Can you contact me there?

**Comment by unixcmddev** [comment]
What is the number? Like mine is talhaazeem#2785

**Comment by unixcmddev** [comment]
Sorry for the inactivity

**Comment by Leonidius20** [comment]
@unixcmddev Leonidius#2397

**Comment by Leonidius20** [comment]
@unixcmddev Can you try this .jar file? I've changed one thing there, but I can't test it. https://drive.google.com/open?id=17_9YlHcKxoerleRNYEiKWyfGvYWqJoPQ
